package com.nexora.sport.model;

/** Catalogo de eventos que pueden generar una {@link Notificacion}. */
public enum TipoNotificacion {
    MEMBRESIA_NUEVA,
    MEMBRESIA_RENOVADA,
    MEMBRESIA_PROXIMA_VENCER,
    MEMBRESIA_VENCE_HOY,
    MEMBRESIA_VENCIDA,

    PAGO_REGISTRADO,
    ABONO_REGISTRADO,
    PAGO_LIQUIDADO,

    RESERVA_CONFIRMADA,
    RESERVA_CANCELADA,
    CLASE_CANCELADA,
    CLASE_HORARIO_CAMBIADO,
    CLASE_INSTRUCTOR_CAMBIADO,
    CLASE_RECORDATORIO,

    ADMIN_MEMBRESIAS_POR_VENCER,
    ADMIN_ALUMNOS_SALDO_PENDIENTE,
    ADMIN_CLASE_CUPO_LLENO,
    ADMIN_ALUMNO_RIESGO_ABANDONO
}
